-- DEBRODER draft product seed
-- Jalankan file ini di Supabase SQL Editor setelah schema produk terbaru tersedia.
-- Produk dibuat aktif dengan gambar placeholder logo DEBRODER.

alter table if exists public.products
  add column if not exists slug text,
  add column if not exists image_url text,
  add column if not exists image_alt text,
  add column if not exists collection_tags text[] not null default '{}',
  add column if not exists intent_tags text[] not null default '{}',
  add column if not exists color_tags text[] not null default '{}',
  add column if not exists size_tags text[] not null default '{}',
  add column if not exists material_tags text[] not null default '{}',
  add column if not exists brand text,
  add column if not exists object_fit text not null default 'cover',
  add column if not exists object_position text not null default 'center center',
  add column if not exists price_label text,
  add column if not exists stock integer not null default 0,
  add column if not exists specifications text[] not null default '{}',
  add column if not exists gallery_urls text[] not null default '{}',
  add column if not exists target_ratio text not null default '4:5',
  add column if not exists focal_x numeric not null default 50,
  add column if not exists focal_y numeric not null default 50,
  add column if not exists focal_zoom numeric not null default 1;

with draft_products as (
  select *
  from (values
    (
      'Kaos Polos Cotton Combed 24s',
      'kaos-polos-cotton-combed-24s',
      'Kaos Polos',
      'Cotton Combed',
      'Kaos polos cotton combed 24s untuk kebutuhan harian, komunitas, brand apparel, event, dan sablon DTF.',
      'Kaos polos 24s untuk custom apparel, komunitas, dan brand.',
      array['Bahan: Cotton Combed 24s', 'Model: Unisex', 'Ukuran: S, M, L, XL, XXL', 'Cocok untuk: Sablon DTF, komunitas, brand apparel']::text[],
      array['kaos-polos', 'basic', 'ready-stock']::text[],
      array['kaos-polos', 'sablon-dtf', 'komunitas', 'brand-apparel', 'tanpa-minimum']::text[],
      array['hitam', 'putih', 'navy', 'abu', 'maroon']::text[],
      array['s', 'm', 'l', 'xl', 'xxl']::text[],
      array['cotton-combed-24s']::text[],
      45000::numeric,
      101
    ),
    (
      'Kaos Polos Cotton Combed 30s',
      'kaos-polos-cotton-combed-30s',
      'Kaos Polos',
      'Cotton Combed',
      'Kaos polos cotton combed 30s dengan karakter lebih ringan untuk brand, komunitas, dan kebutuhan custom.',
      'Kaos polos 30s ringan untuk sablon dan apparel harian.',
      array['Bahan: Cotton Combed 30s', 'Model: Unisex', 'Ukuran: S, M, L, XL, XXL', 'Cocok untuk: Sablon DTF, brand apparel, event']::text[],
      array['kaos-polos', 'basic', 'new-arrival']::text[],
      array['kaos-polos', 'sablon-dtf', 'brand-apparel', 'event', 'tanpa-minimum']::text[],
      array['hitam', 'putih', 'navy', 'abu']::text[],
      array['s', 'm', 'l', 'xl', 'xxl']::text[],
      array['cotton-combed-30s']::text[],
      45000::numeric,
      102
    ),
    (
      'Kaos Polos New State Apparel',
      'kaos-polos-new-state-apparel',
      'Kaos Polos',
      'New State Apparel',
      'Kaos polos New State Apparel untuk kebutuhan retail, komunitas, event, dan produksi apparel custom.',
      'Kaos polos NSA untuk retail dan custom apparel.',
      array['Brand: New State Apparel', 'Model: Unisex', 'Ukuran: S, M, L, XL, XXL', 'Cocok untuk: Retail, komunitas, sablon DTF']::text[],
      array['kaos-polos', 'best-seller', 'ready-stock']::text[],
      array['kaos-polos', 'sablon-dtf', 'komunitas', 'brand-apparel', 'ready-stock']::text[],
      array['hitam', 'putih', 'navy', 'abu']::text[],
      array['s', 'm', 'l', 'xl', 'xxl']::text[],
      array['cotton-combed-24s']::text[],
      45000::numeric,
      103
    ),
    (
      'Polo Shirt NSA',
      'polo-shirt-nsa',
      'Kaos Polos',
      'Polo Shirt NSA',
      'Polo Shirt NSA untuk kantor, komunitas, event, dan kebutuhan seragam dengan tampilan lebih rapi.',
      'Polo Shirt NSA untuk seragam dan event.',
      array['Model: Polo Shirt NSA', 'Ukuran: S, M, L, XL, XXL', 'Cocok untuk: Kantor, komunitas, event', 'Custom: Sablon atau bordir sesuai kebutuhan']::text[],
      array['kaos-polos', 'premium']::text[],
      array['kaos-polos', 'polo-shirt-nsa', 'kantor', 'komunitas', 'event', 'sablon-dtf']::text[],
      array['hitam', 'putih', 'navy', 'abu', 'maroon']::text[],
      array['s', 'm', 'l', 'xl', 'xxl']::text[],
      array['polo-nsa', 'cotton']::text[],
      85000::numeric,
      104
    ),
    (
      'Hoodie Custom',
      'hoodie-custom',
      'Jaket & Hoodie',
      'Hoodie',
      'Hoodie custom untuk komunitas, merchandise, organisasi, dan brand apparel.',
      'Hoodie custom untuk merch dan komunitas.',
      array['Model: Hoodie', 'Ukuran: S, M, L, XL, XXL', 'Cocok untuk: Merchandise, komunitas, organisasi', 'Custom: Sablon DTF atau bordir']::text[],
      array['jaket-hoodie', 'premium']::text[],
      array['jaket-hoodie', 'sablon-dtf', 'bordir', 'komunitas', 'organisasi', 'brand-apparel']::text[],
      array['hitam', 'navy', 'abu', 'maroon']::text[],
      array['s', 'm', 'l', 'xl', 'xxl']::text[],
      array['fleece', 'baby-terry']::text[],
      150000::numeric,
      201
    ),
    (
      'Crewneck Custom',
      'crewneck-custom',
      'Jaket & Hoodie',
      'Crewneck',
      'Crewneck custom untuk brand, komunitas, kantor, dan merchandise dengan tampilan clean.',
      'Crewneck custom untuk brand dan komunitas.',
      array['Model: Crewneck', 'Ukuran: S, M, L, XL, XXL', 'Cocok untuk: Brand, komunitas, kantor', 'Custom: Sablon DTF atau bordir']::text[],
      array['jaket-hoodie', 'premium']::text[],
      array['jaket-hoodie', 'sablon-dtf', 'bordir', 'komunitas', 'brand-apparel']::text[],
      array['hitam', 'navy', 'abu', 'cream']::text[],
      array['s', 'm', 'l', 'xl', 'xxl']::text[],
      array['fleece', 'baby-terry']::text[],
      140000::numeric,
      202
    ),
    (
      'Jaket Custom',
      'jaket-custom',
      'Jaket & Hoodie',
      'Jaket',
      'Jaket custom untuk komunitas, organisasi, event, dan kebutuhan apparel outdoor.',
      'Jaket custom untuk organisasi dan event.',
      array['Model: Jaket', 'Ukuran: S, M, L, XL, XXL', 'Cocok untuk: Organisasi, event, komunitas', 'Custom: Logo, desain, dan identitas tim']::text[],
      array['jaket-hoodie', 'premium']::text[],
      array['jaket-hoodie', 'sablon-dtf', 'bordir', 'komunitas', 'organisasi', 'event']::text[],
      array['hitam', 'navy', 'army', 'abu']::text[],
      array['s', 'm', 'l', 'xl', 'xxl']::text[],
      array['taslan', 'drill', 'fleece']::text[],
      180000::numeric,
      203
    ),
    (
      'Topi Custom Bordir',
      'topi-custom-bordir',
      'Headwear',
      'Topi',
      'Topi custom bordir untuk event, komunitas, kantor, dan merchandise brand.',
      'Topi custom bordir untuk merchandise dan event.',
      array['Model: Topi', 'Ukuran: All Size', 'Cocok untuk: Event, komunitas, kantor', 'Custom: Bordir logo atau teks']::text[],
      array['headwear', 'merchandise']::text[],
      array['headwear', 'bordir', 'merchandise', 'event', 'komunitas']::text[],
      array['hitam', 'putih', 'navy', 'army']::text[],
      array['all-size']::text[],
      array['drill', 'canvas']::text[],
      65000::numeric,
      301
    ),
    (
      'Sablon DTF A4',
      'sablon-dtf-a4',
      'Sablon DTF',
      'A4',
      'Sablon DTF ukuran A4 untuk logo, desain dada, artwork kecil, dan kebutuhan custom satuan.',
      'Sablon DTF A4 untuk desain kecil dan custom satuan.',
      array['Ukuran: Maksimal A4', 'Cocok untuk: Logo, desain dada, artwork kecil', 'File: PNG transparan resolusi tinggi disarankan']::text[],
      array['sablon-dtf', 'tanpa-minimum']::text[],
      array['sablon-dtf', 'kaos-polos', 'desain-custom', 'produksi-satuan', 'tanpa-minimum']::text[],
      array['full-color']::text[],
      array['a4']::text[],
      array['dtf']::text[],
      5000::numeric,
      401
    ),
    (
      'Sablon DTF A3',
      'sablon-dtf-a3',
      'Sablon DTF',
      'A3',
      'Sablon DTF ukuran A3 untuk artwork lebih besar pada kaos, hoodie, jaket, dan apparel custom.',
      'Sablon DTF A3 untuk artwork besar.',
      array['Ukuran: Maksimal A3', 'Cocok untuk: Artwork besar, desain punggung, apparel custom', 'File: PNG transparan resolusi tinggi disarankan']::text[],
      array['sablon-dtf', 'tanpa-minimum']::text[],
      array['sablon-dtf', 'kaos-polos', 'jaket-hoodie', 'desain-custom', 'tanpa-minimum']::text[],
      array['full-color']::text[],
      array['a3']::text[],
      array['dtf']::text[],
      10000::numeric,
      402
    ),
    (
      'Sablon DTF Meteran',
      'sablon-dtf-meteran',
      'Sablon DTF',
      'Meteran',
      'Sablon DTF meteran untuk kebutuhan produksi apparel, reseller, brand, dan repeat order.',
      'Sablon DTF meteran untuk produksi dan reseller.',
      array['Ukuran: Lebar maksimal mengikuti mesin', 'Cocok untuk: Produksi banyak desain, reseller, brand apparel', 'File: Artwork tersusun siap cetak']::text[],
      array['sablon-dtf', 'maklon-dtf']::text[],
      array['sablon-dtf', 'maklon-dtf', 'reseller', 'brand-apparel', 'partai-besar']::text[],
      array['full-color']::text[],
      array['meteran']::text[],
      array['dtf']::text[],
      35000::numeric,
      403
    ),
    (
      'Maklon DTF Brand Apparel',
      'maklon-dtf-brand-apparel',
      'Maklon DTF',
      'Brand Apparel',
      'Layanan maklon DTF untuk brand apparel, reseller, vendor, dan produksi partai besar.',
      'Maklon DTF untuk brand dan reseller.',
      array['Cocok untuk: Brand apparel, reseller, vendor', 'Skala: Produksi berulang dan partai besar', 'Layanan: Konsultasi file, produksi, dan estimasi']::text[],
      array['maklon-dtf', 'brand-apparel']::text[],
      array['maklon-dtf', 'reseller', 'brand-apparel', 'partai-besar', 'produksi-massal']::text[],
      array['full-color']::text[],
      array['custom-size']::text[],
      array['dtf']::text[],
      25000::numeric,
      501
    ),
    (
      'Jersey Futsal Custom',
      'jersey-futsal-custom',
      'Jersey',
      'Futsal',
      'Jersey futsal custom untuk tim, komunitas, sekolah, turnamen, dan event olahraga.',
      'Jersey futsal custom untuk tim dan komunitas.',
      array['Model: Jersey Futsal', 'Ukuran: S, M, L, XL, XXL', 'Custom: Nama, nomor, logo, sponsor', 'Teknik: Cetak sublim']::text[],
      array['jersey', 'custom']::text[],
      array['jersey', 'cetak-sublim', 'sublim', 'tim', 'komunitas', 'nama-nomor']::text[],
      array['custom-color']::text[],
      array['s', 'm', 'l', 'xl', 'xxl']::text[],
      array['dryfit', 'milano']::text[],
      75000::numeric,
      601
    ),
    (
      'Jersey Sepak Bola Custom',
      'jersey-sepak-bola-custom',
      'Jersey',
      'Sepak Bola',
      'Jersey sepak bola custom untuk klub, sekolah, komunitas, turnamen, dan event.',
      'Jersey sepak bola custom untuk klub dan tim.',
      array['Model: Jersey Sepak Bola', 'Ukuran: S, M, L, XL, XXL', 'Custom: Nama, nomor, logo, sponsor', 'Teknik: Cetak sublim']::text[],
      array['jersey', 'custom']::text[],
      array['jersey', 'cetak-sublim', 'sublim', 'tim', 'sekolah', 'nama-nomor']::text[],
      array['custom-color']::text[],
      array['s', 'm', 'l', 'xl', 'xxl']::text[],
      array['dryfit', 'milano']::text[],
      85000::numeric,
      602
    ),
    (
      'Jersey Esports Custom',
      'jersey-esports-custom',
      'Jersey',
      'Esports',
      'Jersey esports custom untuk roster, komunitas gaming, event, dan merchandise tim.',
      'Jersey esports custom untuk tim gaming.',
      array['Model: Jersey Esports', 'Ukuran: S, M, L, XL, XXL', 'Custom: Nama, nickname, logo, sponsor', 'Teknik: Cetak sublim']::text[],
      array['jersey', 'custom']::text[],
      array['jersey', 'cetak-sublim', 'sublim', 'tim', 'komunitas', 'event', 'nama-nomor']::text[],
      array['custom-color']::text[],
      array['s', 'm', 'l', 'xl', 'xxl']::text[],
      array['dryfit', 'milano']::text[],
      85000::numeric,
      603
    ),
    (
      'Jersey Basket Custom',
      'jersey-basket-custom',
      'Jersey',
      'Basket',
      'Jersey basket custom untuk tim, sekolah, komunitas, dan kompetisi.',
      'Jersey basket custom untuk tim.',
      array['Model: Jersey Basket', 'Ukuran: S, M, L, XL, XXL', 'Custom: Nama, nomor, logo, sponsor', 'Teknik: Cetak sublim']::text[],
      array['jersey', 'custom']::text[],
      array['jersey', 'cetak-sublim', 'sublim', 'tim', 'sekolah', 'nama-nomor']::text[],
      array['custom-color']::text[],
      array['s', 'm', 'l', 'xl', 'xxl']::text[],
      array['dryfit', 'milano']::text[],
      85000::numeric,
      604
    ),
    (
      'Jersey Sepeda Custom',
      'jersey-sepeda-custom',
      'Jersey',
      'Sepeda',
      'Jersey sepeda custom untuk komunitas, event, dan kebutuhan apparel olahraga.',
      'Jersey sepeda custom untuk komunitas.',
      array['Model: Jersey Sepeda', 'Ukuran: S, M, L, XL, XXL', 'Custom: Logo, sponsor, nama komunitas', 'Teknik: Cetak sublim']::text[],
      array['jersey', 'custom']::text[],
      array['jersey', 'cetak-sublim', 'sublim', 'komunitas', 'event', 'partai-besar']::text[],
      array['custom-color']::text[],
      array['s', 'm', 'l', 'xl', 'xxl']::text[],
      array['dryfit', 'microfiber']::text[],
      95000::numeric,
      605
    ),
    (
      'Jersey Komunitas Custom',
      'jersey-komunitas-custom',
      'Jersey',
      'Komunitas',
      'Jersey komunitas custom untuk organisasi, kantor, sekolah, kampus, dan gathering.',
      'Jersey komunitas custom untuk organisasi dan event.',
      array['Model: Jersey Komunitas', 'Ukuran: S, M, L, XL, XXL', 'Custom: Logo, nama, nomor, identitas komunitas', 'Teknik: Cetak sublim']::text[],
      array['jersey', 'custom']::text[],
      array['jersey', 'cetak-sublim', 'sublim', 'komunitas', 'organisasi', 'event', 'nama-nomor']::text[],
      array['custom-color']::text[],
      array['s', 'm', 'l', 'xl', 'xxl']::text[],
      array['dryfit', 'milano']::text[],
      85000::numeric,
      606
    ),
    (
      'Cetak Sublim Jersey',
      'cetak-sublim-jersey',
      'Cetak Sublim',
      'Jersey',
      'Cetak sublim untuk jersey custom dengan warna menyeluruh dan detail desain sesuai kebutuhan tim.',
      'Cetak sublim untuk jersey full print.',
      array['Teknik: Sublimasi', 'Cocok untuk: Jersey full print, tim, komunitas', 'Output: Warna menyeluruh mengikuti desain']::text[],
      array['cetak-sublim', 'jersey']::text[],
      array['cetak-sublim', 'sublim', 'jersey', 'tim', 'partai-besar']::text[],
      array['custom-color']::text[],
      array['custom-size']::text[],
      array['dryfit', 'polyester']::text[],
      35000::numeric,
      701
    )
  ) as seed(
    nama,
    slug,
    kategori,
    subcategory,
    deskripsi,
    short_detail,
    specifications,
    collection_tags,
    intent_tags,
    color_tags,
    size_tags,
    material_tags,
    price,
    urutan
  )
)
insert into public.products (
  nama,
  slug,
  kategori,
  subcategory,
  deskripsi,
  short_detail,
  description,
  specifications,
  badge,
  gambar_url,
  image_url,
  image_alt,
  collection_tags,
  intent_tags,
  color_tags,
  size_tags,
  material_tags,
  brand,
  object_fit,
  object_position,
  whatsapp_link,
  link_url,
  price,
  harga,
  price_label,
  stock,
  target_ratio,
  focal_x,
  focal_y,
  focal_zoom,
  urutan,
  status_aktif
)
select
  seed.nama,
  seed.slug,
  seed.kategori,
  seed.subcategory,
  seed.deskripsi,
  seed.short_detail,
  seed.deskripsi,
  seed.specifications,
  '',
  '/brand/debroder/logo-primary-black.png',
  '/brand/debroder/logo-primary-black.png',
  seed.nama,
  seed.collection_tags,
  seed.intent_tags,
  seed.color_tags,
  seed.size_tags,
  seed.material_tags,
  'DEBRODER',
  'contain',
  'center center',
  'https://wa.me/6285355333364',
  case
    when seed.kategori = 'Kaos Polos' then '/kaos-polos'
    when seed.kategori = 'Jaket & Hoodie' then '/jaket-hoodie'
    when seed.kategori = 'Headwear' then '/headwear'
    when seed.kategori = 'Sablon DTF' then '/sablon-dtf'
    when seed.kategori = 'Maklon DTF' then '/maklon-dtf'
    when seed.kategori = 'Jersey' then '/jersey'
    when seed.kategori = 'Cetak Sublim' then '/cetak-sublim'
    else '/koleksi'
  end,
  seed.price,
  seed.price,
  'Mulai dari',
  999,
  '4:5',
  50,
  50,
  1,
  seed.urutan,
  true
from draft_products seed
where not exists (
  select 1
  from public.products existing
  where existing.slug = seed.slug
);

notify pgrst, 'reload schema';
