"use client";

import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import { createSupabaseClient } from "@/lib/supabase";

type Ref={id:string;status:string;updated_at:string|null}|null;
type Props={order:{id:string;status:string;pricing_status:string;payment_balance:number;payment_effective_total:number;payment_production_eligible:boolean;checkout_source:string|null;whatsapp_confirmed_at:string|null};jobOrder:Ref;qualityControl:(Ref&{result?:string|null})|null;fulfillment:Ref};
type Flow={updated_at:string;custom_project_snapshot:unknown;custom_review_started_at:string|null;custom_review_completed_at:string|null;custom_quote_version:number|null;custom_quote_status:string|null;custom_quote_locked_at:string|null;total_amount:number;itemCount:number;lineCount:number;finalVerifiedAt:string|null};
type Stage={index:number;title:string;blocker:string;label:string;href:string;action:"start"|"review"|"quote"|"link"};
const STAGES=["Order Masuk","Review Pesanan","Penetapan Harga","Persetujuan Pelanggan","Pembayaran","Job Order","Produksi","Quality Control","Packing","Pengecekan Akhir","Pengiriman / Pickup","Selesai"];
const REVIEW={product:"Produk valid",variant:"Varian valid",quantity:"Quantity valid",method:"Metode kompatibel",print_size:"Ukuran cetak valid",placement:"Placement valid",design:"Desain dapat diproses",notes:"Catatan jelas",address:"Alamat/penyerahan jelas",feasibility:"Produksi dan deadline realistis"};
const PRICE={product:"Produk sesuai",variant:"Varian sesuai",quantity:"Quantity sesuai",base_price:"Base price PIM sesuai",method:"Metode sesuai",print_size:"Print size sesuai",placement:"Placement sesuai",personalization:"Personalisasi sesuai",design:"Desain sesuai",duplicate_charge:"Tidak ada duplicate charge",setup_fee:"Setup fee valid",adjustments:"Adjustment beralasan",subtotal:"Subtotal benar",final_total:"Total final benar",customer_preview:"Preview pelanggan benar"};

export function CustomOrderOperationalWorkspace(props:Props){
  const [flow,setFlow]=useState<Flow|null>(null);const [selected,setSelected]=useState(0);const [checks,setChecks]=useState<Record<string,boolean>>({});const [note,setNote]=useState("");const [validDays,setValidDays]=useState(7);const [working,setWorking]=useState(false);const [message,setMessage]=useState("");
  const load=useCallback(async()=>{const supabase=createSupabaseClient();if(!supabase)return;const [orderResult,itemResult,fulfillmentResult]=await Promise.all([supabase.from("orders").select("updated_at,custom_project_snapshot,custom_review_started_at,custom_review_completed_at,custom_quote_version,custom_quote_status,custom_quote_locked_at,total_amount").eq("id",props.order.id).maybeSingle(),supabase.from("order_items").select("id",{count:"exact",head:true}).eq("order_id",props.order.id).is("archived_at",null),supabase.from("fulfillments").select("final_verified_at").eq("order_id",props.order.id).is("archived_at",null).neq("status","cancelled").order("created_at",{ascending:false}).limit(1).maybeSingle()]);if(orderResult.error||!orderResult.data){setMessage("State workflow belum dapat dimuat.");return;}setFlow({...(orderResult.data as Omit<Flow,"itemCount"|"lineCount"|"finalVerifiedAt">),itemCount:itemResult.count??0,lineCount:lineCount(orderResult.data.custom_project_snapshot),finalVerifiedAt:fulfillmentResult.data?.final_verified_at??null});},[props.order.id]);
  useEffect(()=>{void load();},[load]);
  const snapshot=flow?.custom_project_snapshot;const custom=Array.isArray(snapshot)&&snapshot.length>0;const stage=resolve(props,flow,custom);
  useEffect(()=>{setSelected(stage.index);setChecks({});},[stage.index]);
  async function act(action:"start"|"review"|"quote"){const supabase=createSupabaseClient();if(!supabase||!flow||working)return;const required=action==="review"?REVIEW:PRICE;if(action!=="start"&&!Object.keys(required).every((key)=>checks[key])){setMessage("Selesaikan seluruh checklist.");return;}if(action==="quote"&&(!Number.isInteger(validDays)||validDays<1||validDays>30)){setMessage("Masa berlaku harus 1–30 hari.");return;}setWorking(true);setMessage("");const result=action==="start"?await supabase.rpc("start_custom_order_review_v1",{p_order_id:props.order.id,p_expected_updated_at:flow.updated_at}):action==="review"?await supabase.rpc("approve_custom_order_review_v1",{p_order_id:props.order.id,p_checklist:checks,p_note:note.trim()||null,p_expected_updated_at:flow.updated_at}):await supabase.rpc("send_custom_order_quotation_v1",{p_order_id:props.order.id,p_checklist:checks,p_valid_days:validDays,p_expected_updated_at:flow.updated_at});setWorking(false);if(result.error){setMessage(result.error.message||"Aksi gagal.");return;}window.location.reload();}
  const toggle=(key:string)=>setChecks({...checks,[key]:!checks[key]});
  return <section className="border border-brand-softGray bg-white"><header className="border-b border-brand-softGray p-5 sm:p-7"><p className="text-xs font-semibold uppercase tracking-[0.14em] text-brand-charcoal/45">Pusat Kendali Order</p><h2 className="mt-2 text-2xl font-semibold">{stage.title}</h2><p className="mt-2 text-sm text-brand-charcoal/60">Satu tahap aktif berasal dari state server. Tahap masa depan tetap terkunci.</p></header>
    <nav aria-label="Tahap Custom Order" className="overflow-x-auto border-b border-brand-softGray p-3"><ol className="flex min-w-max gap-2">{STAGES.map((name,index)=><li key={name}><button type="button" disabled={index>stage.index} onClick={()=>setSelected(index)} aria-current={index===stage.index?"step":undefined} className={`min-h-10 rounded-full border px-4 text-xs font-semibold ${index===selected?"border-brand-green bg-emerald-50 text-brand-green":index<stage.index?"border-brand-softGray bg-brand-offWhite":"border-brand-softGray text-brand-charcoal/40"}`}>{index<stage.index?"✓ ":`${index+1}. `}{name}{index>stage.index?" · terkunci":""}</button></li>)}</ol></nav>
    <div className="grid lg:grid-cols-[300px_minmax(0,1fr)]"><aside className="border-b border-brand-softGray bg-brand-offWhite p-5 lg:sticky lg:top-20 lg:self-start lg:border-b-0 lg:border-r"><dl className="grid gap-3 text-sm"><Summary label="Status" value={props.order.status}/><Summary label="Item" value={String(flow?.itemCount??0)}/><Summary label="Komponen harga" value={String(flow?.lineCount??0)}/><Summary label="Total canonical" value={money(flow?.total_amount??0)}/><Summary label="Quotation" value={flow?.custom_quote_version?`v${flow.custom_quote_version} · ${flow.custom_quote_status}`:"Belum dikirim"}/></dl><p className="mt-5 border border-brand-softGray bg-white p-3 text-sm"><span className="block text-xs text-brand-charcoal/50">Hambatan</span><strong>{stage.blocker}</strong></p></aside>
      <div className="min-w-0 p-5 sm:p-7"><p className="text-xs font-semibold uppercase tracking-[0.12em] text-brand-charcoal/45">{selected<stage.index?"Tahap selesai · baca saja":"Tahap aktif"}</p><h3 className="mt-2 text-xl font-semibold">{STAGES[selected]}</h3>{selected<stage.index?<p className="mt-3 text-sm text-brand-charcoal/60">Selector tidak mengubah status canonical.</p>:stage.action==="start"?<Action text="Snapshot tersedia dan siap direview." button="Mulai Review" working={working} onClick={()=>void act("start")} message={message}/>:stage.action==="review"?<ChecklistAction text="Periksa kelayakan konfigurasi dan produksi." items={REVIEW} checks={checks} toggle={toggle} working={working} button="Setujui Review" onClick={()=>void act("review")} message={message}><label className="mt-4 block text-sm font-semibold">Catatan<textarea rows={3} value={note} onChange={(event)=>setNote(event.target.value)} className="mt-2 w-full border border-brand-softGray p-3 font-normal"/></label></ChecklistAction>:stage.action==="quote"?<ChecklistAction text={`Periksa ${flow?.lineCount??0} komponen sebelum penawaran dikirim.`} items={PRICE} checks={checks} toggle={toggle} working={working} button="Konfirmasi & Kirim ke Pelanggan" onClick={()=>void act("quote")} message={message}><label className="mt-4 block text-sm font-semibold">Masa berlaku<input type="number" min={1} max={30} value={validDays} onChange={(event)=>setValidDays(Number(event.target.value))} className="mt-2 block min-h-11 w-28 border px-3"/></label></ChecklistAction>:<Link href={stage.href} className="mt-5 inline-flex min-h-11 items-center rounded-full bg-brand-green px-5 text-sm font-semibold text-white">{stage.label}</Link>}</div></div></section>;
}

function resolve({order,jobOrder:job,qualityControl:qc,fulfillment}:Props,flow:Flow|null,custom:boolean):Stage{if(new Set(["completed","selesai","picked_up","delivered"]).has(order.status)||["delivered","picked_up"].includes(fulfillment?.status??""))return st(11,"Selesai","Tidak ada","Lihat Histori","#order-history");if(["shipped","in_transit","ready_to_ship","ready_for_pickup"].includes(fulfillment?.status??""))return st(10,"Pengiriman / Pickup","Tidak ada","Buka Fulfillment",`/admin/fulfillments/${fulfillment?.id}`);if(fulfillment?.status==="packing"&&custom&&!flow?.finalVerifiedAt)return st(9,"Pengecekan Akhir","Checklist akhir belum selesai","Buka Pengecekan Akhir",`/admin/fulfillments/${fulfillment.id}`);if(["preparing","packing","problem"].includes(fulfillment?.status??""))return st(8,"Packing","Tidak ada","Lanjutkan Fulfillment",`/admin/fulfillments/${fulfillment?.id}`);if(qc&&qc.result!=="passed")return st(7,"Quality Control","Menunggu hasil QC","Buka Quality Control",`/admin/quality-control?job_order=${job?.id??""}`);if(job&&!["completed","cancelled"].includes(job.status))return st(6,"Produksi","Tidak ada","Buka Job Order",`/admin/job-orders/${job.id}`);if(!job&&order.payment_production_eligible)return st(5,"Job Order","Job Order belum dibuat","Buat / Buka Job Order",`/admin/job-orders?order=${order.id}`);if(custom&&!flow?.custom_review_started_at)return {...st(0,"Order Masuk",order.whatsapp_confirmed_at?"Tidak ada":"Pelanggan belum diverifikasi","Mulai Review","#"),action:"start"};if(custom&&!flow?.custom_review_completed_at)return {...st(1,"Review Pesanan","Review belum disetujui","Setujui Review","#"),action:"review"};if(custom&&flow?.custom_quote_status!=="sent"&&flow?.custom_quote_status!=="locked")return {...st(2,"Penetapan Harga",order.pricing_status!=="final"?"Harga belum final":"Checklist belum dikonfirmasi","Kirim Penawaran","#"),action:"quote"};if(custom&&flow?.custom_quote_status==="sent")return st(3,"Persetujuan Pelanggan","Menunggu keputusan pelanggan","Pantau Persetujuan","#commerce");if(!order.payment_production_eligible)return st(4,"Pembayaran","Menunggu pembayaran","Periksa Pembayaran","#payment");return st(1,"Review Pesanan","Tidak ada","Lanjutkan Review","#order-data");}
function st(index:number,title:string,blocker:string,label:string,href:string):Stage{return{index,title,blocker,label,href,action:"link"};}
function lineCount(value:unknown){return Array.isArray(value)?value.reduce((sum,item)=>{if(!item||typeof item!=="object")return sum;const pricing=(item as {pricing?:{lines?:unknown}}).pricing;return sum+(Array.isArray(pricing?.lines)?pricing.lines.length:0);},0):0;}
function Action({text,button,working,onClick,message}:{text:string;button:string;working:boolean;onClick:()=>void;message:string}){return <div><p className="mt-3 text-sm text-brand-charcoal/60">{text}</p><button type="button" disabled={working} onClick={onClick} className="mt-5 min-h-11 rounded-full bg-brand-green px-5 text-sm font-semibold text-white disabled:opacity-45">{working?"Menyimpan...":button}</button>{message?<p className="mt-3 border border-amber-200 bg-amber-50 p-3 text-sm">{message}</p>:null}</div>;}
function ChecklistAction({text,items,checks,toggle,children,...action}:{text:string;items:Record<string,string>;checks:Record<string,boolean>;toggle:(key:string)=>void;children:React.ReactNode;button:string;working:boolean;onClick:()=>void;message:string}){return <div><p className="mt-3 text-sm text-brand-charcoal/60">{text}</p><fieldset className="mt-5 grid gap-2 sm:grid-cols-2"><legend className="sr-only">Checklist wajib</legend>{Object.entries(items).map(([key,label])=><label key={key} className="flex min-h-11 gap-3 border p-3 text-sm"><input type="checkbox" checked={Boolean(checks[key])} onChange={()=>toggle(key)} className="mt-0.5 h-4 w-4"/>{label}</label>)}</fieldset>{children}<Action text="" {...action}/></div>;}
function Summary({label,value}:{label:string;value:string}){return <div><dt className="text-xs text-brand-charcoal/50">{label}</dt><dd className="mt-1 font-semibold">{value}</dd></div>;}
function money(value:number){return new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0}).format(value||0);}
