"use client";
import Link from "next/link";
import { useCallback,useEffect,useState } from "react";
import { AdminPageHeader } from "@/components/admin/layout/AdminPageHeader";
import { AdminAlert,AdminEmptyState,AdminLoadingState } from "@/components/admin/ui/AdminFeedback";
import { operationsApiFetch } from "@/lib/admin-operations-api";
type Run={id:string;started_at:string;completed_at:string|null;status:string;summary:Record<string,unknown>;error_message:string|null};type Finding={id:string;order_id:string|null;category:string;severity:string;code:string;message:string;status:string;last_seen_at:string;details:Record<string,unknown>;orders:{order_number?:string;customer_name?:string}|null};type Payload={runs:Run[];findings:Finding[];role:string};
export function OperationsHealthAdmin(){const[data,setData]=useState<Payload|null>(null);const[loading,setLoading]=useState(true);const[running,setRunning]=useState(false);const[notice,setNotice]=useState<{type:"success"|"error";text:string}|null>(null);const load=useCallback(async()=>{setLoading(true);try{setData(await operationsApiFetch<Payload>("/api/admin/operations-health"));}catch(error){setNotice({type:"error",text:error instanceof Error?error.message:"Kesehatan sistem belum dapat dimuat."});}finally{setLoading(false);}},[]);useEffect(()=>{void load();},[load]);async function run(){setRunning(true);try{const result=await operationsApiFetch<{result:{status:string;critical:number;warning:number}}>("/api/admin/operations-health",{method:"POST",body:"{}"});setNotice({type:result.result.critical?"error":"success",text:`Rekonsiliasi selesai: ${result.result.critical} kritis, ${result.result.warning} peringatan.`});await load();}catch(error){setNotice({type:"error",text:error instanceof Error?error.message:"Rekonsiliasi gagal."});}finally{setRunning(false);}}
if(loading)return <AdminLoadingState label="Memuat kesehatan operasional..."/>;const open=data?.findings.filter(f=>f.status==="open")??[];const latest=data?.runs[0];return <main className="grid gap-6 text-brand-charcoal"><AdminPageHeader eyebrow="REKONSILIASI" title="Kesehatan Operasional" description="Pemeriksaan terjadwal untuk order, payment, task, outbox, pickup, refund, dan stok lokasi. Task health_reconcile dikecualikan dari pemeriksaan task terminal agar tidak menciptakan loop." actions={<button data-admin-mutation="true" disabled={running} onClick={()=>void run()} className="min-h-11 rounded-full bg-brand-charcoal px-5 text-sm font-semibold text-white">{running?"Memeriksa...":"Jalankan Pemeriksaan"}</button>}/>{notice?<AdminAlert type={notice.type}>{notice.text}</AdminAlert>:null}<section className="grid gap-3 sm:grid-cols-3"><Card label="Status Terakhir" value={latest?.status??"Belum dijalankan"}/><Card label="Temuan Kritis" value={String(open.filter(f=>f.severity==="critical").length)} danger/><Card label="Peringatan" value={String(open.filter(f=>f.severity==="warning").length)}/></section>{open.length?<section className="grid gap-4">{open.map(f=><article key={f.id} className={`border bg-white p-5 ${f.severity==="critical"?"border-red-300":"border-amber-300"}`}><div className="flex flex-wrap justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-[0.12em] text-brand-charcoal/45">{f.category} · {f.code}</p><h2 className="mt-2 font-semibold">{f.message}</h2><p className="mt-1 text-sm text-brand-charcoal/60">{f.orders?.order_number} · {f.orders?.customer_name}</p></div><span className={`h-fit rounded-full px-3 py-1 text-xs font-semibold ${f.severity==="critical"?"bg-red-50 text-red-700":"bg-amber-50 text-amber-800"}`}>{f.severity}</span></div>{f.order_id?<Link href={`/admin/orders/${f.order_id}`} className="mt-4 inline-flex min-h-10 items-center rounded-full bg-brand-charcoal px-4 text-xs font-semibold text-white">Buka Pesanan</Link>:null}</article>)}</section>:<AdminEmptyState title="Tidak ada temuan aktif" description="Jalankan pemeriksaan berkala untuk memastikan sistem tetap sinkron."/>}</main>;}
function Card({label,value,danger}:{label:string;value:string;danger?:boolean}){return <div className={`border bg-white p-5 ${danger&&value!=="0"?"border-red-300":"border-brand-softGray"}`}><p className="text-xs font-semibold uppercase tracking-[0.12em] text-brand-charcoal/45">{label}</p><p className={`mt-2 text-2xl font-semibold ${danger&&value!=="0"?"text-red-700":""}`}>{value}</p></div>;}
