"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { createSupabaseClient } from "@/lib/supabase";

type Summary = {
  payment_requirement_type: string; payment_required_percentage: number;
  payment_required_amount: number | null; payment_effective_total: number;
  payment_production_eligible: boolean;
};
type Payment = { id: string; payment_number: string; amount: number; status: string };
type LinkRow = { id:string;expires_at:string;max_uses:number;used_count:number;revoked_at:string|null;created_by:string|null;archived_at:string|null };
type Adjustment = { id:string;source_payment_id:string;adjustment_type:string;amount:number;effect_amount:number;status:string;reason:string;created_by:string|null;approved_by:string|null;created_at:string };
type Activity = { id:string;action:string;note:string|null;actor_id:string|null;actor_role:string|null;running_balance:number|null;created_at:string };

const VERIFY = ["owner","superadmin","super_admin","admin"];
function money(v:number|null|undefined){return new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0}).format(Number(v||0));}
function dt(v:string){return new Intl.DateTimeFormat("id-ID",{dateStyle:"medium",timeStyle:"short"}).format(new Date(v));}

export function PaymentCompletionPanel({ orderId, summary, payments, role, onChanged }:{orderId:string;summary:Summary;payments:Payment[];role:string;onChanged:()=>Promise<void>}) {
  const [links,setLinks]=useState<LinkRow[]>([]); const [adjustments,setAdjustments]=useState<Adjustment[]>([]); const [activity,setActivity]=useState<Activity[]>([]);
  const [names,setNames]=useState<Record<string,string>>({}); const [busy,setBusy]=useState(false); const [message,setMessage]=useState(""); const [generated,setGenerated]=useState("");
  const [requirement,setRequirement]=useState(summary.payment_requirement_type||"full"); const [percentage,setPercentage]=useState(String(summary.payment_required_percentage||100)); const [requiredAmount,setRequiredAmount]=useState(String(summary.payment_required_amount||0)); const [requirementReason,setRequirementReason]=useState("");
  const verified=useMemo(()=>payments.filter(p=>p.status==="verified"),[payments]);

  async function token(){const s=createSupabaseClient();const {data}=await s?.auth.getSession()??{data:{session:null}};return data.session?.access_token??"";}
  async function api(path:string,init:RequestInit={}){const access=await token();const response=await fetch(path,{...init,headers:{"Content-Type":"application/json",Authorization:`Bearer ${access}`,...init.headers}});const payload=(await response.json()) as {error?:string;[key:string]:unknown};if(!response.ok)throw new Error(payload.error||"Operasi pembayaran gagal.");return payload;}
  const load=useCallback(async()=>{const s=createSupabaseClient();if(!s)return;const [l,a,h]=await Promise.all([s.from("payment_submission_links").select("id,expires_at,max_uses,used_count,revoked_at,created_by,archived_at").eq("order_id",orderId).order("created_at",{ascending:false}),s.from("payment_adjustments").select("id,source_payment_id,adjustment_type,amount,effect_amount,status,reason,created_by,approved_by,created_at").eq("order_id",orderId).order("created_at",{ascending:false}),s.from("payment_activity_history").select("id,action,note,actor_id,actor_role,running_balance,created_at").eq("order_id",orderId).order("created_at",{ascending:false}).limit(100)]);setLinks((l.data||[]) as LinkRow[]);setAdjustments((a.data||[]) as Adjustment[]);setActivity((h.data||[]) as Activity[]);const ids=Array.from(new Set([...(l.data||[]).flatMap(x=>[x.created_by]),...(a.data||[]).flatMap(x=>[x.created_by,x.approved_by]),...(h.data||[]).flatMap(x=>[x.actor_id])].filter((x):x is string=>typeof x==="string")));if(ids.length){const p=await s.from("profiles").select("id,email").in("id",ids);setNames(Object.fromEntries((p.data||[]).map(x=>[x.id,x.email||"Pengguna admin"])));}},[orderId]);
  useEffect(()=>{void load();},[load]);

  async function reissue(){const reason=window.prompt("Alasan menerbitkan ulang tautan pembayaran:")?.trim()||"";if(!reason)return;setBusy(true);setMessage("");try{const p=await api(`/api/admin/orders/${orderId}/payment-links`,{method:"POST",body:JSON.stringify({action:"reissue",reason})});setGenerated(String(p.publicUrl||""));setMessage("Tautan otomatis lama dinonaktifkan dan tautan baru diterbitkan. CTA pelanggan diperbarui pada tracking.");await load();}catch(e){setMessage(e instanceof Error?e.message:"Gagal menerbitkan ulang tautan.");}finally{setBusy(false);}}
  async function linkAction(id:string,action:string){setBusy(true);try{await api(`/api/admin/orders/${orderId}/payment-links`,{method:"PATCH",body:JSON.stringify({linkId:id,action})});await load();}catch(e){setMessage(e instanceof Error?e.message:"Aksi tautan gagal.");}finally{setBusy(false);}}
  async function saveRequirement(e:FormEvent){e.preventDefault();setBusy(true);try{await api(`/api/admin/orders/${orderId}/payment-requirement`,{method:"POST",body:JSON.stringify({type:requirement,percentage:Number(percentage),amount:Number(requiredAmount),reason:requirementReason})});setMessage("Kebijakan pembayaran disimpan.");await onChanged();await load();}catch(x){setMessage(x instanceof Error?x.message:"Kebijakan gagal disimpan.");}finally{setBusy(false);}}
  async function createAdjustment(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);setBusy(true);try{await api("/api/admin/payments/adjustments",{method:"POST",body:JSON.stringify({paymentId:f.get("paymentId"),type:f.get("type"),amount:Number(f.get("amount")),reason:f.get("reason")})});e.currentTarget.reset();setMessage("Koreksi dibuat dan menunggu persetujuan.");await load();}catch(x){setMessage(x instanceof Error?x.message:"Koreksi gagal dibuat.");}finally{setBusy(false);}}
  async function decide(id:string,approve:boolean){const reason=approve?"Disetujui melalui admin":window.prompt("Alasan penolakan koreksi:")||"";setBusy(true);try{await api("/api/admin/payments/adjustments",{method:"PATCH",body:JSON.stringify({adjustmentId:id,approve,reason})});await onChanged();await load();}catch(x){setMessage(x instanceof Error?x.message:"Keputusan koreksi gagal.");}finally{setBusy(false);}}

  return <div className="mt-7 grid gap-6">
    {message?<div className="border border-brand-softGray bg-white p-4 text-sm font-semibold">{message}</div>:null}
    <section className="border border-brand-softGray bg-white p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h3 className="font-semibold">Tautan Pembayaran Otomatis</h3><p className="mt-1 text-sm text-brand-charcoal/55">Aktif otomatis setelah pelanggan terverifikasi dan harga final terkunci. Admin hanya menangani aksi keamanan.</p></div><button disabled={busy} onClick={()=>void reissue()} className="rounded-full border border-brand-charcoal px-4 py-2 text-sm font-semibold disabled:opacity-50">Terbitkan Ulang</button></div>{generated?<div className="mt-4 border border-emerald-200 bg-emerald-50 p-3 text-sm font-semibold">Tautan baru aktif pada CTA tracking pelanggan.</div>:null}<div className="mt-4 grid gap-2">{links.map(x=><div key={x.id} className="flex flex-col justify-between gap-3 border border-brand-softGray p-3 text-sm sm:flex-row sm:items-center"><div><b>{x.revoked_at?"Dicabut":x.archived_at?"Diarsipkan":"Aktif"}</b> · {x.used_count}/{x.max_uses} penggunaan<br/><span className="text-xs text-brand-charcoal/55">Berakhir {dt(x.expires_at)} · Dibuat oleh {x.created_by?names[x.created_by]||"Admin":"Sistem otomatis"}</span></div><div className="flex gap-2">{!x.revoked_at&&!x.archived_at?<button onClick={()=>void linkAction(x.id,"revoke")} className="text-sm font-semibold text-red-700">Nonaktifkan</button>:null}{!x.archived_at?<button onClick={()=>void linkAction(x.id,"archive")} className="text-sm font-semibold">Arsipkan</button>:null}</div></div>)}</div></section>
    {VERIFY.includes(role)?<section className="border border-brand-softGray bg-white p-5"><h3 className="font-semibold">Kebijakan Syarat Pembayaran</h3><form onSubmit={saveRequirement} className="mt-4 grid gap-3 md:grid-cols-4"><select value={requirement} onChange={e=>setRequirement(e.target.value)} className="min-h-11 rounded-lg border border-brand-softGray px-3"><option value="full">Lunas 100%</option><option value="percentage">Persentase minimum</option><option value="deposit">DP nominal</option><option value="fixed">Nominal minimum</option></select><input type="number" min="0" max="100" value={percentage} onChange={e=>setPercentage(e.target.value)} disabled={requirement!=="percentage"} className="min-h-11 rounded-lg border border-brand-softGray px-3" placeholder="Persentase"/><input type="number" min="0" value={requiredAmount} onChange={e=>setRequiredAmount(e.target.value)} disabled={!['fixed','deposit'].includes(requirement)} className="min-h-11 rounded-lg border border-brand-softGray px-3" placeholder="Nominal"/><input value={requirementReason} onChange={e=>setRequirementReason(e.target.value)} className="min-h-11 rounded-lg border border-brand-softGray px-3" placeholder="Alasan kebijakan khusus"/><button disabled={busy} className="min-h-11 bg-brand-charcoal px-4 text-sm font-semibold text-white md:col-span-4">Simpan Kebijakan</button></form><p className="mt-3 text-sm">Efektif dibayar: <b>{money(summary.payment_effective_total)}</b> · Layak produksi: <b>{summary.payment_production_eligible?"Ya":"Belum"}</b></p></section>:null}
    {VERIFY.includes(role)?<section className="border border-brand-softGray bg-white p-5"><h3 className="font-semibold">Koreksi Pembayaran</h3><form onSubmit={createAdjustment} className="mt-4 grid gap-3 md:grid-cols-4"><select name="paymentId" required className="min-h-11 rounded-lg border border-brand-softGray px-3"><option value="">Pilih pembayaran</option>{verified.map(p=><option key={p.id} value={p.id}>{p.payment_number} · {money(p.amount)}</option>)}</select><select name="type" className="min-h-11 rounded-lg border border-brand-softGray px-3"><option value="adjustment_credit">Penambahan</option><option value="adjustment_debit">Pengurangan</option><option value="reversal">Pembalikan</option><option value="refund">Pengembalian Dana</option><option value="void">Pembatalan Nilai</option></select><input name="amount" type="number" min="1" required className="min-h-11 rounded-lg border border-brand-softGray px-3" placeholder="Nominal"/><input name="reason" required className="min-h-11 rounded-lg border border-brand-softGray px-3" placeholder="Alasan wajib"/><button disabled={busy} className="min-h-11 bg-brand-charcoal px-4 text-sm font-semibold text-white md:col-span-4">Buat Koreksi</button></form><div className="mt-4 grid gap-2">{adjustments.map(a=><div key={a.id} className="flex flex-col justify-between gap-3 border border-brand-softGray p-3 text-sm sm:flex-row sm:items-center"><div><b>{a.adjustment_type.replaceAll('_',' ')}</b> · {money(a.effect_amount)} · {a.status}<br/><span className="text-xs text-brand-charcoal/55">{a.reason} · {a.created_by?names[a.created_by]||"Admin":"Sistem"} · {dt(a.created_at)}</span></div>{a.status==='pending'?<div className="flex gap-2"><button onClick={()=>void decide(a.id,true)} className="font-semibold text-emerald-700">Setujui</button><button onClick={()=>void decide(a.id,false)} className="font-semibold text-red-700">Tolak</button></div>:null}</div>)}</div></section>:null}
    <section className="border border-brand-softGray bg-white p-5"><h3 className="font-semibold">Riwayat Pembayaran</h3><div className="mt-4 grid gap-2">{activity.map(h=><div key={h.id} className="border-l-2 border-brand-green py-1 pl-4 text-sm"><b>{h.action.replaceAll('_',' ')}</b>{h.note?` · ${h.note}`:""}<br/><span className="text-xs text-brand-charcoal/55">{h.actor_id?names[h.actor_id]||h.actor_role||"Admin":"Pelanggan/Sistem"} · {dt(h.created_at)}{h.running_balance==null?"":` · Sisa ${money(h.running_balance)}`}</span></div>)}{!activity.length?<p className="text-sm text-brand-charcoal/55">Belum ada riwayat Phase 5B.</p>:null}</div></section>
  </div>;
}
