"use client";

import { type FormEvent, useCallback, useEffect, useState } from "react";
import { AdminPageHeader } from "@/components/admin/layout/AdminPageHeader";
import { AdminAlert, AdminEmptyState, AdminLoadingState } from "@/components/admin/ui/AdminFeedback";
import { operationsApiFetch } from "@/lib/admin-operations-api";

type Cancellation = { id:string;order_id:string;reason:string;status:string;requires_refund:boolean;verified_amount_snapshot:number;requested_at:string;decision_reason:string|null;orders:{order_number?:string;customer_name?:string;status?:string;payment_status?:string;total_amount?:number}|null };
type Refund = { id:string;refund_number:string;order_id:string;amount:number;status:string;sent_at:string|null;orders:{order_number?:string;customer_name?:string}|null;refund_evidence:Array<{id:string;file_name:string;transfer_reference:string;transferred_at:string}> };
type Payload={requests:Cancellation[];refunds:Refund[];role:string};

export function RefundOperationsAdmin(){
  const [data,setData]=useState<Payload|null>(null);const[loading,setLoading]=useState(true);const[working,setWorking]=useState("");const[notice,setNotice]=useState<{type:"success"|"error";text:string}|null>(null);
  const load=useCallback(async()=>{setLoading(true);try{setData(await operationsApiFetch<Payload>("/api/admin/refunds"));}catch(error){setNotice({type:"error",text:error instanceof Error?error.message:"Refund belum dapat dimuat."});}finally{setLoading(false);}},[]);
  useEffect(()=>{void load();},[load]);
  async function decide(row:Cancellation,approve:boolean){const reason=window.prompt(approve?"Alasan menyetujui pembatalan:":"Alasan menolak pembatalan:");if(!reason||reason.trim().length<3)return;setWorking(row.id);try{await operationsApiFetch("/api/admin/refunds",{method:"POST",body:JSON.stringify({action:"decide_cancellation",requestId:row.id,approve,reason})});setNotice({type:"success",text:"Keputusan pembatalan berhasil disimpan."});await load();}catch(error){setNotice({type:"error",text:error instanceof Error?error.message:"Keputusan belum dapat diproses."});}finally{setWorking("");}}
  async function upload(event:FormEvent<HTMLFormElement>,refund:Refund){event.preventDefault();setWorking(refund.id);const form=new FormData(event.currentTarget);try{await operationsApiFetch(`/api/admin/refunds/${refund.id}/evidence`,{method:"POST",body:form});setNotice({type:"success",text:"Bukti refund tervalidasi di storage dan pembatalan diselesaikan."});await load();}catch(error){setNotice({type:"error",text:error instanceof Error?error.message:"Bukti refund belum dapat diproses."});}finally{setWorking("");}}
  if(loading)return <AdminLoadingState label="Memuat pembatalan dan refund..."/>;
  const pending=data?.requests.filter(r=>r.status==="pending")??[];
  return <main className="grid gap-6 text-brand-charcoal"><AdminPageHeader eyebrow="PEMBATALAN & DANA" title="Pembatalan dan Refund" description="Pembatalan tanpa pembayaran diselesaikan langsung. Order dengan dana terverifikasi wajib melalui alokasi refund dan bukti transfer yang benar-benar ada di storage."/>{notice?<AdminAlert type={notice.type}>{notice.text}</AdminAlert>:null}
    <section className="grid gap-4"><h2 className="text-xl font-semibold">Perlu Keputusan</h2>{pending.length?pending.map(row=><article key={row.id} className="border border-brand-softGray bg-white p-5"><div className="flex flex-wrap justify-between gap-4"><div><h3 className="font-semibold">{row.orders?.order_number} · {row.orders?.customer_name}</h3><p className="mt-2 text-sm leading-6 text-brand-charcoal/65">{row.reason}</p></div><div className="text-right text-sm"><p>Dana terverifikasi</p><strong>{money(row.verified_amount_snapshot)}</strong></div></div><div className="mt-4 flex gap-2"><button data-admin-mutation="true" disabled={working===row.id} onClick={()=>void decide(row,true)} className="min-h-10 rounded-full bg-brand-green px-4 text-xs font-semibold text-white">Setujui</button><button data-admin-mutation="true" disabled={working===row.id} onClick={()=>void decide(row,false)} className="min-h-10 rounded-full border border-red-300 px-4 text-xs font-semibold text-red-700">Tolak</button></div></article>):<AdminEmptyState title="Tidak ada permintaan pembatalan baru" description="Permintaan pelanggan akan masuk ke antrean ini secara otomatis."/>}</section>
    <section className="grid gap-4"><h2 className="text-xl font-semibold">Kasus Refund</h2>{data?.refunds.length?data.refunds.map(refund=><article key={refund.id} className="border border-brand-softGray bg-white p-5"><div className="flex flex-wrap justify-between gap-4"><div><h3 className="font-semibold">{refund.refund_number} · {refund.orders?.order_number}</h3><p className="mt-1 text-sm text-brand-charcoal/60">{refund.orders?.customer_name} · {refund.status.replaceAll("_"," ")}</p></div><strong>{money(refund.amount)}</strong></div>{refund.refund_evidence.length?<div className="mt-4 rounded-xl bg-emerald-50 p-4 text-sm text-emerald-900">Bukti tersimpan · {refund.refund_evidence[0].transfer_reference}</div>:(["approved","processing","failed"].includes(refund.status)?<form onSubmit={(e)=>void upload(e,refund)} className="mt-4 grid gap-3 border-t border-brand-softGray pt-4 sm:grid-cols-2"><label className="grid gap-2 text-sm font-semibold">Referensi transfer<input name="reference" required minLength={3} className="min-h-11 border border-brand-softGray px-3"/></label><label className="grid gap-2 text-sm font-semibold">Waktu transfer<input name="transferredAt" type="datetime-local" required className="min-h-11 border border-brand-softGray px-3"/></label><label className="grid gap-2 text-sm font-semibold sm:col-span-2">Bukti transfer<input name="proof" type="file" accept="image/png,image/jpeg,application/pdf" required className="border border-brand-softGray p-3"/></label><button data-admin-mutation="true" disabled={working===refund.id} className="min-h-11 rounded-full bg-brand-charcoal px-5 text-sm font-semibold text-white sm:col-span-2">Validasi Bukti & Selesaikan Refund</button></form>:null)}</article>):<AdminEmptyState title="Belum ada kasus refund" description="Kasus dibuat setelah pembatalan order berbayar disetujui."/>}</section>
  </main>;
}
function money(value:number){return new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0}).format(Number(value||0));}
