import Image from "next/image";
import Link from "next/link";
import { BrochureShell } from "@/components/brochure/BrochureShell";
import { ConsultationSection, container, Eyebrow } from "@/components/brochure/BrochureContent";
import { brochureWhatsappUrl } from "@/src/config/site";
import type { BrochureProduct } from "@/src/data/products";

export function BrochureProductDetail({ product }: { product: BrochureProduct }) {
  return <BrochureShell><article className={`${container} pb-20 pt-8 sm:pb-28 sm:pt-12`}><nav aria-label="Breadcrumb" className="mb-8 flex gap-2 text-xs text-[#666761]"><Link href="/" className="underline-offset-4 hover:underline">Beranda</Link><span aria-hidden="true">/</span><Link href="/produk" className="underline-offset-4 hover:underline">Produk</Link><span aria-hidden="true">/</span><span aria-current="page" className="text-[#20211f]">{product.name}</span></nav><div className="grid items-center gap-12 lg:grid-cols-[1.06fr_0.94fr] lg:gap-20"><figure><div className="relative aspect-[5/5] bg-[#e9e8e2]"><Image src={product.image} alt={product.imageAlt} fill priority sizes="(max-width: 1024px) 100vw, 52vw" className="object-contain p-8 sm:p-12" /></div><figcaption className="mt-3 text-[11px] uppercase tracking-[0.14em] text-[#85847d]">Visual referensi · foto bahan menyusul</figcaption></figure><div><Eyebrow>Material / bahan</Eyebrow><h1 className="mt-5 text-[clamp(2.8rem,5.4vw,5.3rem)] font-medium leading-[0.99] tracking-[-0.06em]">{product.name}</h1><p className="mt-7 max-w-lg text-lg leading-8 text-[#454640]">{product.description}</p><p className="mt-5 max-w-lg text-sm leading-7 text-[#6b6b64]">{product.detail}</p><div className="mt-8 border-t border-[#d4d1c8] pt-8"><p className="mb-5 text-xs text-[#77776f]">Harga dan ketersediaan dikonfirmasi saat konsultasi.</p><a href={brochureWhatsappUrl(`Halo DEBRODER, saya ingin bertanya tentang ${product.name}.`)} target="_blank" rel="noopener noreferrer" className="inline-flex min-h-12 items-center justify-center bg-[#20211f] px-6 text-sm font-semibold text-white transition hover:bg-[#44453e] focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-[#806b48]">Tanyakan Produk <span className="sr-only">(buka WhatsApp di tab baru)</span><span aria-hidden="true" className="ml-5">↗</span></a></div></div></div></article><ConsultationSection /></BrochureShell>;
}
