
begin;
create temporary table cpd(sku text primary key,slug text unique,nama text,cat_slug text,kategori text,sub_slug text,subcategory text,price integer,summary text,material text) on commit drop;
insert into cpd values
('DBR-CC24','cotton-combed-24s','Kaos Cotton Combed 24s','kaos-polos','Kaos Polos','cotton-combed','Cotton Combed',45000,'Kaos harian berbahan Cotton Combed 24s dengan pilihan warna dan ukuran yang mudah disesuaikan.','Cotton Combed 24s'),
('DBR-3600','3600-soft-tee','Kaos Polos NSA','kaos-polos','Kaos Polos','new-state-apparel','New State Apparel',45000,'Kaos polos New State Apparel dengan pilihan warna dan ukuran untuk kebutuhan harian maupun produksi custom.','Spesifikasi pemasok belum lengkap'),
('DBR-8100','8100-polo','Polo Shirt Polos','kaos-polos','Kaos Polos','polo-shirt','Polo Shirt',60000,'Polo shirt polos berkerah untuk kebutuhan seragam, komunitas, dan tampilan kasual yang rapi.','Spesifikasi pemasok belum lengkap'),
('DBR-72Y00','72y00-youth','Kaos Polos Anak Cotton Combed','kaos-polos','Kaos Polos','kaos-polos-anak','Kaos Polos Anak',37000,'Kaos polos anak berbahan Cotton Combed dengan pilihan warna dan ukuran yang tercatat per varian.','Cotton Combed'),
('DBR-PULLOVER','pullover-hooded','Hoodie Fleece','jaket-hoodie','Jaket & Hoodie','hoodie','Hoodie',140000,'Hoodie berbahan fleece dengan pilihan warna dan ukuran untuk pemakaian harian dan kebutuhan custom.','Fleece'),
('DBR-CREWNECK','crewneck','Crewneck Fleece','jaket-hoodie','Jaket & Hoodie','crewneck','Crewneck',100000,'Crewneck berbahan fleece tanpa tudung dengan pilihan warna dan ukuran untuk pemakaian harian.','Fleece'),
('DBR-BOMBER','bomber-jacket','Bomber Jacket Custom','jaket-hoodie','Jaket & Hoodie','bomber-jacket','Bomber Jacket',205000,'Jaket model bomber untuk kebutuhan custom dengan pilihan warna dan ukuran yang tercatat per varian.','Spesifikasi pemasok belum lengkap'),
('DBR-WINDBREAKER','windbreaker','Windbreaker Custom','jaket-hoodie','Jaket & Hoodie','windbreaker','Windbreaker',185000,'Jaket model windbreaker untuk kebutuhan custom dengan pilihan warna dan ukuran berbasis varian.','Spesifikasi pemasok belum lengkap'),
('DBR-ZIPHOOD','zip-hooded','Zip Hoodie Custom','jaket-hoodie','Jaket & Hoodie','zip-hoodie','Zip Hoodie',150000,'Hoodie beritsleting untuk kebutuhan custom dengan pilihan warna dan ukuran yang tercatat per varian.','Spesifikasi pemasok belum lengkap'),
('DBD-HDWR','6089-premium-classic-snapback','Topi Custom','headwear','Headwear','topi','Topi',30000,'Topi snapback custom dengan pengatur ukuran dan stok yang divalidasi sebelum checkout.','80% acrylic dan 20% wool; camo 60% cotton dan 40% polyester');
do $$ begin if(select count(*) from cpd t join public.products p on p.slug=t.slug and upper(btrim(p.sku))=t.sku)<>10 then raise exception 'canonical physical mapping failed'; end if; end $$;
insert into public.product_subcategories(category_id,name,slug,description,public_label,is_active,admin_notes)
select distinct c.id,t.subcategory,t.sub_slug,'Canonical owner-locked product subcategory.',t.subcategory,true,'Canonical Product Data V1' from cpd t join public.product_categories c on c.slug=t.cat_slug
where not exists(select 1 from public.product_subcategories s where s.category_id=c.id and s.slug=t.sub_slug);
update public.products p set nama=t.nama,name=t.nama,kategori=t.kategori,subcategory=t.subcategory,product_category_id=c.id,product_subcategory_id=s.id,deskripsi=t.summary,short_detail=t.summary,
description=t.summary||' Warna, ukuran, SKU, dan stok mengikuti varian PIM. Harga akhir dihitung ulang oleh server setelah ukuran dan jumlah dipilih. Pilih ukuran yang biasa digunakan; ukuran 2XL ke atas memiliki penyesuaian harga. Ikuti petunjuk pada label produk untuk pencucian dan perawatan.',
specifications=array['Material: '||t.material,'Warna dan ukuran: mengikuti varian PIM','Stok: divalidasi per SKU','Harga: dihitung ulang oleh server','Perawatan: ikuti label produk'],
seo_title=t.nama||' | DEBRODER',seo_description=t.summary,canonical_url='/produk/'||t.slug,image_alt=t.nama||' DEBRODER',product_type='standard_product',pricing_mode='variant_based',sales_mode='ready_stock',tier_scope='none',has_variants=true,uses_configurator=false,minimum_order_qty=1,base_price=t.price,price=t.price,harga=t.price,compare_price=null,price_label=null,badge='',updated_at=now()
from cpd t join public.product_categories c on c.slug=t.cat_slug join public.product_subcategories s on s.category_id=c.id and s.slug=t.sub_slug where p.slug=t.slug and upper(btrim(p.sku))=t.sku;
with j(sku,slug,nama,sub_slug,subcategory,price,summary) as(values
('DBR-JRS-FUTSAL','jersey-futsal-custom','Jersey Futsal Custom','jersey-futsal','Futsal',100000,'Jersey futsal custom dengan konfigurasi model, warna, ukuran, identitas tim, dan jumlah pemain.'),
('DBR-JRS-FOOTBALL','jersey-sepak-bola-custom','Jersey Sepak Bola Custom','jersey-sepak-bola','Sepak Bola',130000,'Jersey sepak bola custom dengan konfigurasi model, warna, ukuran, identitas tim, dan jumlah pemain.'))
update public.products p set nama=j.nama,name=j.nama,kategori='Jersey',subcategory=j.subcategory,product_category_id=c.id,product_subcategory_id=s.id,deskripsi=j.summary,short_detail=j.summary,description=j.summary||' Lengkapi konfigurasi melalui Jersey Configurator; harga akhir divalidasi oleh server.',specifications=array['Alur: Jersey Configurator','Harga: divalidasi oleh server','Produksi: setelah detail dan desain disetujui'],seo_title=j.nama||' | DEBRODER',seo_description=j.summary,canonical_url='/produk/'||j.slug,image_alt=j.nama||' DEBRODER',product_type='configurable_product',pricing_mode='configurator_based',sales_mode='custom',tier_scope='none',has_variants=false,uses_configurator=true,base_price=j.price,price=j.price,harga=j.price,price_label=null,badge='',link_url='/jersey/configurator?product='||j.slug,updated_at=now()
from j join public.product_categories c on c.slug='jersey' join public.product_subcategories s on s.category_id=c.id and s.slug=j.sub_slug where p.slug=j.slug and upper(btrim(p.sku))=j.sku;
update public.services set nama=case slug when 'sablon-dtf-a4' then 'Sablon DTF A4' when 'sablon-dtf-a3' then 'Sablon DTF A3' else 'Sablon DTF Meteran' end,category_key='sablon-dtf',deskripsi=case slug when 'sablon-dtf-a4' then 'Layanan Sablon DTF ukuran A4 dengan harga exact Rp20.000.' when 'sablon-dtf-a3' then 'Layanan Sablon DTF ukuran A3 dengan harga exact Rp25.000.' else 'Layanan Sablon DTF meteran dengan harga exact Rp30.000 per meter.' end,detail_body='File desain dan detail kebutuhan diperiksa dalam alur layanan sebelum produksi.',harga_mulai=case slug when 'sablon-dtf-a4' then 20000 when 'sablon-dtf-a3' then 25000 else 30000 end,updated_at=now() where slug in('sablon-dtf-a4','sablon-dtf-a3','sablon-dtf-meteran');
update public.product_variant_sizes x set price_adjustment=case when upper(regexp_replace(btrim(x.size_name),'[^A-Za-z0-9]+','','g')) in('S','M','L','XL') then 0 when upper(regexp_replace(btrim(x.size_name),'[^A-Za-z0-9]+','','g')) in('2XL','XXL') then 10000 when upper(regexp_replace(btrim(x.size_name),'[^A-Za-z0-9]+','','g')) in('3XL','XXXL') then 20000 when upper(regexp_replace(btrim(x.size_name),'[^A-Za-z0-9]+','','g')) in('4XL','XXXXL') then 30000 when upper(regexp_replace(btrim(x.size_name),'[^A-Za-z0-9]+','','g'))='5XL' then 40000 else x.price_adjustment end,updated_at=now()
from public.product_variants v join public.products p on p.id=v.product_id join cpd t on t.slug=p.slug and t.sku=upper(btrim(p.sku)) where x.variant_id=v.id;
do $$ begin if(select count(*) from public.inventory_locations where active and location_type='store' and upper(btrim(name))='STORE PETTARANI')<>1 then raise exception 'inventory location mapping failed'; end if; end $$;
insert into public.inventory_balances(location_id,variant_size_id,on_hand_quantity,reserved_quantity)
select l.id,x.id,0,0 from public.inventory_locations l cross join cpd t join public.products p on p.slug=t.slug and upper(btrim(p.sku))=t.sku join public.product_variants v on v.product_id=p.id and v.status='active' and v.is_active is not false join public.product_variant_sizes x on x.variant_id=v.id and x.status='active' and x.is_active is not false where l.active and l.location_type='store' and upper(btrim(l.name))='STORE PETTARANI' on conflict(location_id,variant_size_id) do nothing;
create temporary table ca on commit drop as select l.id location_id,x.id variant_size_id,b.on_hand_quantity before_on_hand,(100-coalesce(sum(ab.on_hand_quantity) filter(where al.active and al.location_type<>'legacy'),0))::integer delta
from cpd t join public.products p on p.slug=t.slug and upper(btrim(p.sku))=t.sku join public.product_variants v on v.product_id=p.id and v.status='active' and v.is_active is not false join public.product_variant_sizes x on x.variant_id=v.id and x.status='active' and x.is_active is not false join public.inventory_locations l on l.active and l.location_type='store' and upper(btrim(l.name))='STORE PETTARANI' join public.inventory_balances b on b.location_id=l.id and b.variant_size_id=x.id left join public.inventory_balances ab on ab.variant_size_id=x.id left join public.inventory_locations al on al.id=ab.location_id
where not exists(select 1 from public.inventory_movements m where m.idempotency_key='canonical-product-v1:'||x.id::text) group by l.id,x.id,b.on_hand_quantity having coalesce(sum(ab.on_hand_quantity) filter(where al.active and al.location_type<>'legacy'),0)<100;
update public.inventory_balances b set on_hand_quantity=b.on_hand_quantity+a.delta,updated_at=now() from ca a where b.location_id=a.location_id and b.variant_size_id=a.variant_size_id;
insert into public.inventory_movements(idempotency_key,variant_size_id,location_id,movement_type,quantity_delta,balance_after,on_hand_after,reserved_after,available_after,reason)
select 'canonical-product-v1:'||a.variant_size_id::text,a.variant_size_id,a.location_id,'adjustment',a.delta,a.before_on_hand+a.delta,a.before_on_hand+a.delta,b.reserved_quantity,a.before_on_hand+a.delta-b.reserved_quantity,'Owner-locked canonical opening stock: aggregate 100 units per valid trial variant' from ca a join public.inventory_balances b on b.location_id=a.location_id and b.variant_size_id=a.variant_size_id on conflict(idempotency_key) do nothing;
do $$ declare bad integer; begin with q as(select x.id,coalesce(sum(b.on_hand_quantity) filter(where l.active and l.location_type<>'legacy'),0) qty from cpd t join public.products p on p.slug=t.slug and upper(btrim(p.sku))=t.sku join public.product_variants v on v.product_id=p.id and v.status='active' and v.is_active is not false join public.product_variant_sizes x on x.variant_id=v.id and x.status='active' and x.is_active is not false left join public.inventory_balances b on b.variant_size_id=x.id left join public.inventory_locations l on l.id=b.location_id group by x.id) select count(*) into bad from q where qty<>100; if bad<>0 then raise exception 'opening stock postcheck failed: %',bad; end if; end $$;
insert into public.system_audit_log(entity_type,action,actor_role,source,reason,metadata) values('product_catalog','canonical_product_data_publication_readiness_v1_applied','owner','migration','Canonical product identity, content, SEO, price, size adjustment, and idempotent opening inventory.',jsonb_build_object('physical_products',10,'jersey_products',2,'services',3,'opening_stock_per_valid_variant',100,'publication_state_changed',false,'rls_changed',false,'historical_orders_changed',false));
commit;;
