drop trigger if exists audit_orders_changes on public.orders;
create trigger audit_orders_changes after insert or update or delete on public.orders for each row execute function public.audit_row_change();
drop trigger if exists audit_order_payments_changes on public.order_payments;
create trigger audit_order_payments_changes after insert or update or delete on public.order_payments for each row execute function public.audit_row_change();
drop trigger if exists audit_payment_submission_links_changes on public.payment_submission_links;
create trigger audit_payment_submission_links_changes after insert or update or delete on public.payment_submission_links for each row execute function public.audit_row_change();
drop trigger if exists audit_payment_adjustments_changes on public.payment_adjustments;
create trigger audit_payment_adjustments_changes after insert or update or delete on public.payment_adjustments for each row execute function public.audit_row_change();
drop trigger if exists audit_document_number_rules_changes on public.document_number_rules;
create trigger audit_document_number_rules_changes after insert or update or delete on public.document_number_rules for each row execute function public.audit_row_change();
drop trigger if exists audit_notifications_changes on public.notifications;
create trigger audit_notifications_changes after insert or update or delete on public.notifications for each row execute function public.audit_row_change();
drop trigger if exists audit_quotations_changes on public.quotations;
create trigger audit_quotations_changes after insert or update or delete on public.quotations for each row execute function public.audit_row_change();
drop trigger if exists audit_mockup_sets_changes on public.mockup_sets;
create trigger audit_mockup_sets_changes after insert or update or delete on public.mockup_sets for each row execute function public.audit_row_change();;
